version: '3.4'

services:
  rabbitmq:
    image: "rabbitmq:3.9-management"
    hostname: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  ticketsql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-container-tickets
    environment:
      - SA_PASSWORD=Ticket123456$
      - ACCEPT_EULA=Y

  tickets.microservice:
    image: ${DOCKER_REGISTRY-}ticketsmicroservice
    container_name: tickets-microservice
    build:
      context: .
      dockerfile: Tickets.Microservice/Dockerfile
    ports:
      - "5020:80"
      - "5021:443"
    depends_on:
      - ticketsql
      - rabbitmq
 
  supportsql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-container-support
    environment:
      - SA_PASSWORD=Support123456$
      - ACCEPT_EULA=Y

  support.microservice:
    image: ${DOCKER_REGISTRY-}supportmicroservice
    container_name: support-microservice
    build:
      context: .
      dockerfile: Support.Microservice/Dockerfile
    ports:
      - "5030:80"
      - "5031:443"
    depends_on:
      - supportsql
      - rabbitmq
